# TCL File Generated by Component Editor 15.0
# Tue Dec 20 18:01:32 CST 2022
# DO NOT MODIFY


# 
# Wrapper "Wrapper" v1.0
#  2022.12.20.18:01:32
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module Wrapper
# 
set_module_property DESCRIPTION ""
set_module_property NAME Wrapper
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Wrapper
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file VGA_display.sv SYSTEM_VERILOG PATH VGA_display.sv
add_fileset_file Wrapper.sv SYSTEM_VERILOG PATH Wrapper.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter S_IDLE STD_LOGIC_VECTOR 0
set_parameter_property S_IDLE DEFAULT_VALUE 0
set_parameter_property S_IDLE DISPLAY_NAME S_IDLE
set_parameter_property S_IDLE TYPE STD_LOGIC_VECTOR
set_parameter_property S_IDLE UNITS None
set_parameter_property S_IDLE ALLOWED_RANGES 0:3
set_parameter_property S_IDLE HDL_PARAMETER true
add_parameter S_DISPLAY STD_LOGIC_VECTOR 1
set_parameter_property S_DISPLAY DEFAULT_VALUE 1
set_parameter_property S_DISPLAY DISPLAY_NAME S_DISPLAY
set_parameter_property S_DISPLAY TYPE STD_LOGIC_VECTOR
set_parameter_property S_DISPLAY UNITS None
set_parameter_property S_DISPLAY ALLOWED_RANGES 0:3
set_parameter_property S_DISPLAY HDL_PARAMETER true
add_parameter display_start STD_LOGIC_VECTOR 1
set_parameter_property display_start DEFAULT_VALUE 1
set_parameter_property display_start DISPLAY_NAME display_start
set_parameter_property display_start TYPE STD_LOGIC_VECTOR
set_parameter_property display_start UNITS None
set_parameter_property display_start ALLOWED_RANGES 0:3
set_parameter_property display_start HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_master_0
# 
add_interface avalon_master_0 avalon start
set_interface_property avalon_master_0 addressUnits SYMBOLS
set_interface_property avalon_master_0 associatedClock clock_sink
set_interface_property avalon_master_0 associatedReset reset_sink
set_interface_property avalon_master_0 bitsPerSymbol 8
set_interface_property avalon_master_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_master_0 burstcountUnits WORDS
set_interface_property avalon_master_0 doStreamReads false
set_interface_property avalon_master_0 doStreamWrites false
set_interface_property avalon_master_0 holdTime 0
set_interface_property avalon_master_0 linewrapBursts false
set_interface_property avalon_master_0 maximumPendingReadTransactions 0
set_interface_property avalon_master_0 maximumPendingWriteTransactions 0
set_interface_property avalon_master_0 readLatency 0
set_interface_property avalon_master_0 readWaitTime 1
set_interface_property avalon_master_0 setupTime 0
set_interface_property avalon_master_0 timingUnits Cycles
set_interface_property avalon_master_0 writeWaitTime 0
set_interface_property avalon_master_0 ENABLED true
set_interface_property avalon_master_0 EXPORT_OF ""
set_interface_property avalon_master_0 PORT_NAME_MAP ""
set_interface_property avalon_master_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_master_0 avm_address address Output 5
add_interface_port avalon_master_0 avm_read read Output 1
add_interface_port avalon_master_0 avm_readdata readdata Input 32
add_interface_port avalon_master_0 avm_write write Output 1
add_interface_port avalon_master_0 avm_writedata writedata Output 32
add_interface_port avalon_master_0 avm_waitrequest waitrequest Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock ""
set_interface_property avalon_slave_0 associatedReset ""
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 o_VGA_B readdata Output 8
add_interface_port avalon_slave_0 o_VGA_G readdata Output 8
add_interface_port avalon_slave_0 o_VGA_R readdata Output 8
add_interface_port avalon_slave_0 o_VGA_blank writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 o_VGA_HS writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 o_VGA_VS writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 o_VGA_sync writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 o_VGA_clk writeresponsevalid_n Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink avm_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink avm_rst reset Input 1

